### ISSUE TITLE
Contribution to the wiki

### ISSUE THREAD

**Issue by kaptain-kavern** [Tammabanana/GreyFluffs-Fantasy-Animals#2]
Hiya,

I was about to add some resources-links in the wiki, in order to get everyone on the same page regarding coding/xml knowledge, but ...                    

As the wiki isn't done yet, I can't even create/edit pages for now.

---

I was wanting to add the sidebar I have made in my fork, [here](https://github.com/kaptain-kavern/GreyFluffs-Fantasy-Animals/wiki)

---

Someone with collaborator rights should create the wiki. Or directly paste this code in the wikisidebar : 

```
## Modding/coding help - resources : 
* [RimWorld XML Database](https://github.com/RimWorldMod/RimworldModdingFiles) - _(xml files explained)_
* [RimWorld XML Auto-Documentation](https://ludeon.com/forums/index.php?topic=21440.0) - _list of all Core uses of RimWorld's XML code_
* [Modding 101](https://github.com/RimWorldMod/RimworldModdingFiles/wiki)

## Animal modding
* [Animals data Spreadsheet](https://docs.google.com/spreadsheets/d/13rgQecI_4Z6-olG9PCO-6uSVyC5cmXh6_Wp_v-Xt8FI/pubhtml#)
* [Some animals definitions/values explained](https://github.com/kaptain-kavern/CK_AnimalPlant_Pack/wiki/Modding)
```

Best regards

**Comment by Tammabanana** [comment]
Added you as a collaborator! Also clicked the button to create the first wiki page, though I did nothing new to it.

**Comment by Tammabanana** [comment]
Well, I _thought_ I'd created the first wiki page... maybe I didn't click save. I've copy/pasted the code into the sidebar. Assuming I did it right.

**Comment by kaptain-kavern** [comment]
Hey I just got the collaborator request. Thanks 

And yes you did the sidebar right :wink:
