### ISSUE TITLE
Is an "Issue" possibly the best way to upload art for a new animal?

### ISSUE THREAD

**Issue by Tammabanana** [Tammabanana/GreyFluffs-Fantasy-Animals#3]
Looks like you can attach files here. Testing it out with GreyFluffs' original posts' art - 
![kirinside](https://cloud.githubusercontent.com/assets/23137648/19831689/6089305e-9dde-11e6-9292-5f062d50a1c2.png)
![reddragonside](https://cloud.githubusercontent.com/assets/23137648/19831690/629fed42-9dde-11e6-9b63-0cbc207a8c93.png)
![testwyvside](https://cloud.githubusercontent.com/assets/23137648/19831691/6459fde4-9dde-11e6-83c0-e76b22d8e34b.png)

**Comment by Tammabanana** [comment]
It kind of looks like you can drag the images, but I couldn't drag-and-drop directly from here to the Textures folder. Is there an easy way to move image files from here to there, in the browser interface? Or is it best to download them from here, and re-upload?

**Comment by kaptain-kavern** [comment]
I'm using windows and firefox, and I can drag'n'drop directly from here to any folder (else you could right click > save as, no?).

But I really thing the more easiest way is using the application (https://desktop.github.com/). When you get used to the whole "github thinggy" (took me some time at first)

**Comment by Tammabanana** [comment]
I can do browser->local folders fine, but not browser-tab->browser-tab. It does look easier to mess with files locally and upload through the app, I'm fiddling with it now.

**Comment by Tammabanana** [comment]
You're right. It works a lot better having downloaded the whole thing through the GitHub app, opening the local folder for the art in question, and dragging it from there over to the issue.
